package robertoCafagna.BE_capstone.enums;

public enum NotificationType {
    FOLLOW, LIKE, COMMENT, COMMENT_REPLY, MESSAGE, EVENT_INVITE, EVENT_UPDATED,
    PARTICIPATION_REQUEST, PARTICIPATION_ACCEPTED, PARTICIPATION_REJECTED,
    ACCESS_CODE_REQUEST, ACCESS_CODE_GRANTED, SYSTEM,
}
